services:
  db:
    image: postgres:16
    container_name: animehub_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-animehub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-animehub}
      POSTGRES_DB: ${POSTGRES_DB:-animehub}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - animehub_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: animehub_redis
    ports:
      - "6379:6379"

volumes:
  animehub_pg:
